interface Classroom {
  id: number;
  name: string;
  code: string;
  instructor: string;
  school: string;
  section: string;
  startDate: string;
  endDate: string;
  status: "active" | "inactive";
  // action column still needed
}

export const classrooms: Classroom[] = [
  {
    id: 1,
    name: "Software Engineering",
    code: "COSC 40943",
    instructor: "Dr. Wei",
    school: "Texas Christian University",
    section: "LEC 030",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 2,
    name: "Deep Learning",
    code: "COSC 40523",
    instructor: "Dr. Pandey",
    school: "Texas Christian University",
    section: "LEC 074",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 3,
    name: "OOP and Design Patterns",
    code: "COSC 40453",
    instructor: "Dr. Wei",
    school: "Texas Christian University",
    section: "LEC 060",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 4,
    name: "Cloud Computing",
    code: "COSC 40233",
    instructor: "Dr. Sarkar",
    school: "Texas Christian University",
    section: "LEC 080",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "inactive",
  },
  {
    id: 5,
    name: "Data Structures",
    code: "COSC 20803",
    instructor: "Dr. Miller",
    school: "Texas Christian University",
    section: "LEC 012",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 6,
    name: "Operating Systems",
    code: "COSC 30203",
    instructor: "Dr. Thompson",
    school: "Texas Christian University",
    section: "LEC 041",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 7,
    name: "Database Systems",
    code: "COSC 30403",
    instructor: "Dr. Nguyen",
    school: "Texas Christian University",
    section: "LEC 021",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "inactive",
  },
  {
    id: 8,
    name: "Computer Networks",
    code: "COSC 30603",
    instructor: "Dr. Patel",
    school: "Texas Christian University",
    section: "LEC 033",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 9,
    name: "Cybersecurity Fundamentals",
    code: "COSC 30713",
    instructor: "Dr. Rhodes",
    school: "Texas Christian University",
    section: "LEC 010",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 10,
    name: "Algorithms",
    code: "COSC 30103",
    instructor: "Dr. Shah",
    school: "Texas Christian University",
    section: "LEC 052",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 11,
    name: "Mobile App Development",
    code: "COSC 40323",
    instructor: "Dr. Kim",
    school: "Texas Christian University",
    section: "LEC 014",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "inactive",
  },
  {
    id: 12,
    name: "Game Development",
    code: "COSC 31223",
    instructor: "Dr. Hernandez",
    school: "Texas Christian University",
    section: "LEC 046",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 13,
    name: "Human-Computer Interaction",
    code: "COSC 40913",
    instructor: "Dr. Larson",
    school: "Texas Christian University",
    section: "LEC 051",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 14,
    name: "Machine Learning",
    code: "COSC 40513",
    instructor: "Dr. Vyas",
    school: "Texas Christian University",
    section: "LEC 015",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "inactive",
  },
  {
    id: 15,
    name: "Web Application Development",
    code: "COSC 40213",
    instructor: "Dr. Brooks",
    school: "Texas Christian University",
    section: "LEC 017",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 16,
    name: "Intro to Computer Science",
    code: "COSC 10403",
    instructor: "Dr. Simmons",
    school: "Texas Christian University",
    section: "LEC 001",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 17,
    name: "Ethics in Computing",
    code: "COSC 40843",
    instructor: "Dr. Jordan",
    school: "Texas Christian University",
    section: "LEC 028",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "inactive",
  },
  {
    id: 18,
    name: "Computer Architecture",
    code: "COSC 30303",
    instructor: "Dr. Bennett",
    school: "Texas Christian University",
    section: "LEC 032",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 19,
    name: "Data Visualization",
    code: "COSC 40963",
    instructor: "Dr. Yang",
    school: "Texas Christian University",
    section: "LEC 066",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "active",
  },
  {
    id: 20,
    name: "Computational Biology",
    code: "COSC 40973",
    instructor: "Dr. Alvarez",
    school: "Texas Christian University",
    section: "LEC 039",
    startDate: "08/18/2025",
    endDate: "12/08/2025",
    status: "inactive",
  },
];
