<template>
  <div class="container py-2 mx-auto">
    <DataTable :columns="columns" :data="data" />
  </div>
</template>

<script setup lang="ts">
import type { Instructor } from "../../InstructorDatatable/columns";
import { onMounted, ref } from "vue";
import { columns } from "../../InstructorDatatable/columns";
import DataTable from "../../InstructorDatatable/data-table.vue";

const data = ref<Instructor[]>([]);

async function getData(): Promise<Instructor[]> {
  // Fetch data from your API here.
  return [
    {
      id: 0,
      name: "Professor 0",
      email: "prof0@tcu.edu",
      school: "Texas Christian University",
      classroom: 0,
      status: "active",
    },
    {
      id: 1,
      name: "Professor 1",
      email: "prof1@tcu.edu",
      school: "Texas Christian University",
      classroom: 1,
      status: "active",
    },
    {
      id: 2,
      name: "Professor 2",
      email: "prof2@tcu.edu",
      school: "Texas Christian University",
      classroom: 2,
      status: "deactived",
    },
    {
      id: 3,
      name: "Professor 3",
      email: "prof3@tcu.edu",
      school: "Texas Christian University",
      classroom: 3,
      status: "active",
    },
    {
      id: 4,
      name: "Professor 4",
      email: "prof4@tcu.edu",
      school: "Texas Christian University",
      classroom: 4,
      status: "active",
    },
    {
      id: 5,
      name: "Professor 5",
      email: "prof5@tcu.edu",
      school: "Texas Christian University",
      classroom: 5,
      status: "deactived",
    },
    {
      id: 6,
      name: "Professor 6",
      email: "prof6@tcu.edu",
      school: "Texas Christian University",
      classroom: 6,
      status: "active",
    },
    {
      id: 7,
      name: "Professor 7",
      email: "prof7@tcu.edu",
      school: "Texas Christian University",
      classroom: 7,
      status: "active",
    },
    {
      id: 8,
      name: "Professor 8",
      email: "prof8@tcu.edu",
      school: "Texas Christian University",
      classroom: 8,
      status: "deactived",
    },
    {
      id: 9,
      name: "Professor 9",
      email: "prof9@tcu.edu",
      school: "Texas Christian University",
      classroom: 9,
      status: "active",
    },
    {
      id: 10,
      name: "Professor 10",
      email: "prof10@tcu.edu",
      school: "Texas Christian University",
      classroom: 10,
      status: "active",
    },
    {
      id: 11,
      name: "Professor 11",
      email: "prof11@tcu.edu",
      school: "Texas Christian University",
      classroom: 11,
      status: "deactived",
    },
    {
      id: 12,
      name: "Professor 12",
      email: "prof12@tcu.edu",
      school: "Texas Christian University",
      classroom: 12,
      status: "active",
    },
    {
      id: 13,
      name: "Professor 13",
      email: "prof13@tcu.edu",
      school: "Texas Christian University",
      classroom: 13,
      status: "active",
    },
    {
      id: 14,
      name: "Professor 14",
      email: "prof14@tcu.edu",
      school: "Texas Christian University",
      classroom: 14,
      status: "deactived",
    },
    {
      id: 15,
      name: "Professor 15",
      email: "prof15@tcu.edu",
      school: "Texas Christian University",
      classroom: 15,
      status: "active",
    },
    {
      id: 16,
      name: "Professor 16",
      email: "prof16@tcu.edu",
      school: "Texas Christian University",
      classroom: 16,
      status: "active",
    },
    {
      id: 17,
      name: "Professor 17",
      email: "prof17@tcu.edu",
      school: "Texas Christian University",
      classroom: 17,
      status: "deactived",
    },
    {
      id: 18,
      name: "Professor 18",
      email: "prof18@tcu.edu",
      school: "Texas Christian University",
      classroom: 18,
      status: "active",
    },
    {
      id: 19,
      name: "Professor 19",
      email: "prof19@tcu.edu",
      school: "Texas Christian University",
      classroom: 19,
      status: "active",
    },
    {
      id: 20,
      name: "Professor 20",
      email: "prof20@tcu.edu",
      school: "Texas Christian University",
      classroom: 20,
      status: "deactived",
    },
    {
      id: 21,
      name: "Professor 21",
      email: "prof21@tcu.edu",
      school: "Texas Christian University",
      classroom: 21,
      status: "active",
    },
    {
      id: 22,
      name: "Professor 22",
      email: "prof22@tcu.edu",
      school: "Texas Christian University",
      classroom: 22,
      status: "active",
    },
    {
      id: 23,
      name: "Professor 23",
      email: "prof23@tcu.edu",
      school: "Texas Christian University",
      classroom: 23,
      status: "deactived",
    },
    {
      id: 24,
      name: "Professor 24",
      email: "prof24@tcu.edu",
      school: "Texas Christian University",
      classroom: 24,
      status: "active",
    },
    {
      id: 25,
      name: "Professor 25",
      email: "prof25@tcu.edu",
      school: "Texas Christian University",
      classroom: 25,
      status: "active",
    },
    {
      id: 26,
      name: "Professor 26",
      email: "prof26@tcu.edu",
      school: "Texas Christian University",
      classroom: 26,
      status: "deactived",
    },
    {
      id: 27,
      name: "Professor 27",
      email: "prof27@tcu.edu",
      school: "Texas Christian University",
      classroom: 27,
      status: "active",
    },
    {
      id: 28,
      name: "Professor 28",
      email: "prof28@tcu.edu",
      school: "Texas Christian University",
      classroom: 28,
      status: "active",
    },
    {
      id: 29,
      name: "Professor 29",
      email: "prof29@tcu.edu",
      school: "Texas Christian University",
      classroom: 29,
      status: "deactived",
    },
    {
      id: 30,
      name: "Professor 30",
      email: "prof30@tcu.edu",
      school: "Texas Christian University",
      classroom: 30,
      status: "active",
    },
    {
      id: 31,
      name: "Professor 31",
      email: "prof31@tcu.edu",
      school: "Texas Christian University",
      classroom: 31,
      status: "active",
    },
    {
      id: 32,
      name: "Professor 32",
      email: "prof32@tcu.edu",
      school: "Texas Christian University",
      classroom: 32,
      status: "deactived",
    },
    {
      id: 33,
      name: "Professor 33",
      email: "prof33@tcu.edu",
      school: "Texas Christian University",
      classroom: 33,
      status: "active",
    },
    {
      id: 34,
      name: "Professor 34",
      email: "prof34@tcu.edu",
      school: "Texas Christian University",
      classroom: 34,
      status: "active",
    },
    {
      id: 35,
      name: "Professor 35",
      email: "prof35@tcu.edu",
      school: "Texas Christian University",
      classroom: 35,
      status: "deactived",
    },
    {
      id: 36,
      name: "Professor 36",
      email: "prof36@tcu.edu",
      school: "Texas Christian University",
      classroom: 36,
      status: "active",
    },
    {
      id: 37,
      name: "Professor 37",
      email: "prof37@tcu.edu",
      school: "Texas Christian University",
      classroom: 37,
      status: "active",
    },
    {
      id: 38,
      name: "Professor 38",
      email: "prof38@tcu.edu",
      school: "Texas Christian University",
      classroom: 38,
      status: "deactived",
    },
    {
      id: 39,
      name: "Professor 39",
      email: "prof39@tcu.edu",
      school: "Texas Christian University",
      classroom: 39,
      status: "active",
    },
    {
      id: 40,
      name: "Professor 40",
      email: "prof40@tcu.edu",
      school: "Texas Christian University",
      classroom: 40,
      status: "active",
    },
    {
      id: 41,
      name: "Professor 41",
      email: "prof41@tcu.edu",
      school: "Texas Christian University",
      classroom: 41,
      status: "deactived",
    },
    {
      id: 42,
      name: "Professor 42",
      email: "prof42@tcu.edu",
      school: "Texas Christian University",
      classroom: 42,
      status: "active",
    },
    {
      id: 43,
      name: "Professor 43",
      email: "prof43@tcu.edu",
      school: "Texas Christian University",
      classroom: 43,
      status: "active",
    },
    {
      id: 44,
      name: "Professor 44",
      email: "prof44@tcu.edu",
      school: "Texas Christian University",
      classroom: 44,
      status: "deactived",
    },
    {
      id: 45,
      name: "Professor 45",
      email: "prof45@tcu.edu",
      school: "Texas Christian University",
      classroom: 45,
      status: "active",
    },
    {
      id: 46,
      name: "Professor 46",
      email: "prof46@tcu.edu",
      school: "Texas Christian University",
      classroom: 46,
      status: "active",
    },
    {
      id: 47,
      name: "Professor 47",
      email: "prof47@tcu.edu",
      school: "Texas Christian University",
      classroom: 47,
      status: "deactived",
    },
    {
      id: 48,
      name: "Professor 48",
      email: "prof48@tcu.edu",
      school: "Texas Christian University",
      classroom: 48,
      status: "active",
    },
    {
      id: 49,
      name: "Professor 49",
      email: "prof49@tcu.edu",
      school: "Texas Christian University",
      classroom: 49,
      status: "active",
    },
  ];
}

onMounted(async () => {
  data.value = await getData();
});
</script>


